---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Stop and remove Docker instance
      community.docker.docker_container:
        name: instance
        state: absent